apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noderediotaddon.fullname" . }}
  labels:
    {{- include "noderediotaddon.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "noderediotaddon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "noderediotaddon.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      serviceAccountName: {{ include "noderediotaddon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dockerRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVICE_BINDINGS
              value: {{ .Values.iot.edge.bindings | quote }}
            - name: IOT_SERVICE_INSTANCE_ID
              value: {{ .Values.iot.edge.serviceInstanceId | quote }}
          volumeMounts:
          - name: tls-storage
            mountPath: "{{ required "required for certificateDir" .Values.certificateDir }}"
            readOnly: true
          ports:
            - name: http
              containerPort: 16008
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: tls-storage
        secret:
          secretName: secret-tls-properties
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
