apiVersion: v2
appVersion: 1.0.0
description: node-red-iot-addon
name: noderediotaddon
type: application
version: 0.0.3
icon: https://www.sap.com/content/dam/application/shared/logos/sap-logo-svg.svg
