apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ps-ref-app-stateful
  labels:
    app: ps-ref-app
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
          app: ps-ref-app
          service: persistence-service-ref-app
    serviceName: persistence-service-ref-app
    updateStrategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: ps-ref-app
                service: persistence-service-ref-app
        spec:
            securityContext:
              fsGroup: 1000
              runAsUser: 1000
            containers:
              - name: persistence-service-ref-app
                image: {{ .Values.dockerRegistry }}/persistence-service-ref-app{{ .Values.containerImageSuffix }}:{{ required "A valid value is required for containerImageVersion" .Values.containerImageVersion }}
                imagePullPolicy: {{ required "A valid value is required for imagePullPolicy." .Values.imagePullPolicy }}
                env:
                  - name: LOG_LEVEL
                    value: "{{ required "A valid value is required for log level" .Values.logLevel  }}"
                  - name: MAX_IN_FLIGHT
                    value: "{{ required "A valid value is required for max in flight" .Values.maxInFlight  }}"
                  - name: CERTIFICATES_DIRECTORY
                    value: "{{ required "A valid value is required for certificateDir" .Values.certificateDir  }}"
                  - name: SERVICE_BINDINGS
                    value: {{ .Values.iot.edge.bindings | quote }}
                volumeMounts:
                  - mountPath: "{{ required "A valid value is required for certificateDir" .Values.certificateDir }}"
                    name: ps-ref-app-tls-storage
                    readOnly: true
            imagePullSecrets:
              - name: {{ .Values.imagePullSecret }}
            volumes:
              - name: ps-ref-app-tls-storage
                secret:
                  secretName: ps-ref-app-secret-tls-properties
                  defaultMode: 0400
